version: '3'
networks:
  devmeter_net:
    name: devmeter_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    networks:
      devmeter_net:
        ipv4_address: 172.22.0.3
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - "./mongodb/data/db:/data/db"
      - "./mongodb/init:/docker-entrypoint-initdb.d"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    networks:
      devmeter_net:
        ipv4_address: 172.22.0.4
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    networks:
      devmeter_net:
        ipv4_address: 172.22.0.5
    ports:
      - "3000:3000"
    volumes:
      - ./metabase/metabase.db:/metabase.db
  presto:
    image: prestodb:0.257
    container_name: presto
    networks: 
      devmeter_net:
        ipv4_address: 172.22.0.6
    ports:
      - "8080:8080"
  logstash:
    build: ./logstash/
    container_name: logstash
    volumes:
      - ./logstash/config/:/usr/share/logstash/config/ 
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      devmeter_net: 
        ipv4_address: 172.22.0.7
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      LS_OPTS: "--config.reload.automatic  --config.reload.interval 20"
      TW_CONSUMER_KEY: ${TW_CONSUMER_KEY}
      TW_CONSUMER_SECRET: ${TW_CONSUMER_SECRET}
      TW_OAUTH_TOKEN: ${TW_OAUTH_TOKEN}
      TW_OAUTH_TOKEN_SECRET: ${TW_OAUTH_TOKEN_SECRET}
    restart: always
    depends_on:
      - "mongodb"
volumes:
  mongo_data:
    driver: local